image: python:3.13

stages:
- lint
- test
- deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_JOB_NAME}
  paths:
  - .cache/pip
  - venv/

before_script:
- python -m venv venv
- source venv/bin/activate
- python -m pip install --upgrade pip
- pip install -r requirements.txt

linting:
  stage: lint
  script:
  - pip install flake8
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

testing:
  stage: test
  script:
  - pytest --cov=calc --cov-report=term --cov-report=html --junitxml=report.xml
  coverage: '/^TOTAL.*\s+(\d+\%)/'
  artifacts:
    reports:
      junit: report.xml
    paths:
    - htmlcov/

pages:
  stage: deploy
  script:
  - mv htmlcov/ public/
  - 'echo "Coverage report is available at: https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/"'
  artifacts:
    paths:
    - public
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'